version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies
      - cd "$CODEBUILD_SRC_DIR/frontend"
      - npm install
  build:
    commands:
      - echo Building frontend
      - cd "$CODEBUILD_SRC_DIR/frontend"
      - npm run build
      - echo Building backend
      - cd "$CODEBUILD_SRC_DIR/backend"
      - chmod +x ./gradlew
      - ./gradlew clean bootJar -x test
      - chmod +x "$CODEBUILD_SRC_DIR/deploy-scripts/"*.sh

artifacts:
  base-directory: .
  files:
    - appspec.yml
    - deploy-scripts/**/*
    - frontend/dist/**/*
    - backend/build/libs/*.jar
